### ISSUE TITLE
Vibration Problem

### ISSUE THREAD

**Issue by senolatac** [Yuliang-Lee/el-table-fixed-header#2]
When I scroll it down, vibration occurs on header. It's most probably related with scroll-change amount.

**Comment by Yuliang-Lee** [comment]
This phenomenon seems to be related to the operating system, browser and screen resolution. I just can reproduces this in my MacOS inner screen and no occur in windows's any browser or screen

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
chedongming, @yinzj1993, @jacobzheng, @softminer, @caishaowu, @rclijia, @m3ngyang, @nomad003, @zoollcar, @visitor-demo, @desword, @PengShaw, @chowaikong, @xinpengfei520, @Justice-love, @elliotxx, @seeyan246789, @misterchenleiya, @susyimes, @PMLLLLL, @xeoshow, @SeanDragon, @Kumisama, @wander2016, @WaterEye0o, @lwangreen, @uxlsl, @twingella, @wl461749287, @yongkangCS, @zysidea, @sunxingboo, @zhifanXU17, @xiayouge, @shanyuhu, @creamidea, @GCSimba, @CTZV, @hwlsniper, @rodneyzhang, @by2101, @kuokuo, @sagexueqi, @JinghuangLiu, @ultrazhangster, @ceoluo, @ycliu912, @wang4343852, @Firmach0, @davidchai
